pipeline{
    agent any
    stages {
        stage('hello world test'){
            steps{
                script{
                    hellolaunch.greeting ' World !'
                }
            }
        }
    }
}